name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *" # roda a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman Graph
        uses: Platane/snk@v3
        with:
          github_user_name: souzajean
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push to repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}